# Matrix creating using mod 7,5 

In [5]:
# TODO: index matrix and weights; calculate rowise cost; calculate rowise mean and std. dev.

In [7]:
import pandas as pd
import numpy as np
from constants import PATH, CONSTRAINTS

Loading

In [21]:
data = pd.read_excel(PATH)
data

Unnamed: 0              Name Position  Skill  Salary (€M)
0            0       Alex Carter       GK     85             90
1            1      Jordan Smith       GK     88            100
2            2     Ryan Mitchell       GK     83             85
3            3    Chris Thompson       GK     80             80
4            4   Blake Henderson       GK     87             95
5            5     Daniel Foster      DEF     90            110
6            6     Lucas Bennett      DEF     85             90
7            7       Owen Parker      DEF     88            100
8            8      Ethan Howard      DEF     80             70
9            9        Mason Reed      DEF     82             75
10          10      Logan Brooks      DEF     86             95
11          11      Caleb Fisher      DEF     84             85
12          12     Nathan Wright      MID     92            120
13          13      Connor Hayes      MID     89            105
14          14      Dylan Morgan      MID     91            115
15          15     Hunter Cooper      MID     83             85
16          16     Austin Torres      MID     82             80
17          17  Gavin Richardson      MID     87             95
18          18      Spencer Ward      MID     84             85
19          19   Sebastian Perry      FWD     95            150
20          20     Xavier Bryant      FWD     90            120
21          21    Elijah Sanders      FWD     93            140
22          22    Adrian Collins      FWD     85             90
23          23     Tyler Jenkins      FWD     80             70
24          24      Chase Murphy      FWD     86             95
25          25     Landon Powell      FWD     89            110
26          26      Julian Scott      FWD     92            130
27          27    Bentley Rivera      MID     88            100
28          28    Maxwell Flores      DEF     81             72
29          29      Dominic Bell      MID     86             95
30          30     Jaxon Griffin      DEF     79             65
31          31   Ashton Phillips      MID     90            110
32          32       Colton Gray      FWD     91            125
33          33    Brayden Hughes      DEF     87            100
34          34    Zachary Nelson      FWD     86             92

In [9]:
# Load the data
data = pd.read_excel(PATH, index_col='Unnamed: 0')

# Define the custom order based on the PARTITIONS dictionary keys
custom_order = list(PARTITIONS.keys())

# Set the custom order in the 'position' column using pd.Categorical
data['Position'] = pd.Categorical(
    data['Position']
    , categories=custom_order
    , ordered=True
    )

# Sort data by Position
data = data.sort_values(by='Position')

# Reset the indices to obtain a unique Id
data.reset_index(inplace=True, drop=True)
data.reset_index(inplace=True)

# Transform to np array
data = np.array(data)

NameError: name 'PARTITIONS' is not defined

In [10]:
data

Name Position  Skill  Salary (€M)
0        Alex Carter       GK     85             90
1       Jordan Smith       GK     88            100
2      Ryan Mitchell       GK     83             85
3     Chris Thompson       GK     80             80
4    Blake Henderson       GK     87             95
5      Daniel Foster      DEF     90            110
6      Lucas Bennett      DEF     85             90
7        Owen Parker      DEF     88            100
8       Ethan Howard      DEF     80             70
9         Mason Reed      DEF     82             75
10      Logan Brooks      DEF     86             95
11      Caleb Fisher      DEF     84             85
12     Nathan Wright      MID     92            120
13      Connor Hayes      MID     89            105
14      Dylan Morgan      MID     91            115
15     Hunter Cooper      MID     83             85
16     Austin Torres      MID     82             80
17  Gavin Richardson      MID     87             95
18      Spencer Ward      MID     84             85
19   Sebastian Perry      FWD     95            150
20     Xavier Bryant      FWD     90            120
21    Elijah Sanders      FWD     93            140
22    Adrian Collins      FWD     85             90
23     Tyler Jenkins      FWD     80             70
24      Chase Murphy      FWD     86             95
25     Landon Powell      FWD     89            110
26      Julian Scott      FWD     92            130
27    Bentley Rivera      MID     88            100
28    Maxwell Flores      DEF     81             72
29      Dominic Bell      MID     86             95
30     Jaxon Griffin      DEF     79             65
31   Ashton Phillips      MID     90            110
32       Colton Gray      FWD     91            125
33    Brayden Hughes      DEF     87            100
34    Zachary Nelson      FWD     86             92

Drafting

In [ ]:
# Assign the values of the array, using the properties of modulo 5 to distribute the unique Ids by column
shape = (5,7)
my_matrix = np.empty(shape=shape)

for i in range(shape[1]):
    for j in range(shape[0]):
        my_matrix[j][i] = data[shape[0] * i + j][0]

my_matrix

KeyError: -1

In [ ]:
ind_cost_matrix = np.array([[
        data[int(index), -1] for index in row
    ] for row in my_matrix
])

ind_cost_matrix

NameError: name 'my_matrix' is not defined

In [31]:
my_matrix = np.array([
    [1., 6., 11., 17., 22., 27., 32.],
    [4., 8., 13., 19., 24., 26., 31.],
    [0., 7., 12., 15., 20., 28., 33.],
    [2., 5., 10., 16., 21., 29., 34.],
    [3., 9., 14., 18., 23., 25., 30.]
], dtype=int)

weights = data.iloc[:, 4:].to_numpy()

print(weights)

[[ 90]
 [100]
 [ 85]
 [ 80]
 [ 95]
 [110]
 [ 90]
 [100]
 [ 70]
 [ 75]
 [ 95]
 [ 85]
 [120]
 [105]
 [115]
 [ 85]
 [ 80]
 [ 95]
 [ 85]
 [150]
 [120]
 [140]
 [ 90]
 [ 70]
 [ 95]
 [110]
 [130]
 [100]
 [ 72]
 [ 95]
 [ 65]
 [110]
 [125]
 [100]
 [ 92]]


In [32]:

np.all(np.sum(weights[my_matrix], axis=1) <= 750)

np.False_

In [33]:
weights[my_matrix]

array([[[100],
        [ 90],
        [ 85],
        [ 95],
        [ 90],
        [100],
        [125]],

       [[ 95],
        [ 70],
        [105],
        [150],
        [ 95],
        [130],
        [110]],

       [[ 90],
        [100],
        [120],
        [ 85],
        [120],
        [ 72],
        [100]],

       [[ 85],
        [110],
        [ 95],
        [ 80],
        [140],
        [ 95],
        [ 92]],

       [[ 80],
        [ 75],
        [115],
        [ 85],
        [ 70],
        [110],
        [ 65]]])

In [69]:
team_cost_matrix = [
    sum(
        data[int(index), -1] for index in row
    ) for row in my_matrix
]

team_cost_matrix

[692, 710, 750, 680, 592]

In [64]:
team_skill_matrix = np.array([(
        np.mean(
            [data[int(index), -2] for index in row]
        ), np.std(
            [data[int(index), -2] for index in row]
        )
    ) for row in my_matrix
])

team_skill_matrix

array([[86.57142857,  4.16986272],
       [87.42857143,  3.88613443],
       [88.14285714,  3.60272006],
       [86.14285714,  4.05069911],
       [83.71428571,  2.86427681]])

In [67]:
team_std = np.std(team_skill_matrix[:, 0])

team_std

np.float64(1.51023717558886)

#### Column selector, for mutation

In [ ]:
import random

j = random.randint(0, 7)

state = random.random() * j < .5 * j

print(state * ((-1)**(j+1)))
    
my_matrix